version: '3'

services:
  qr-generator:
    build: .
    container_name: qr-generator
    environment:
      - QR_DATA_URL=https://github.com/your-username
      - QR_CODE_DIR=qr_codes
      - QR_CODE_FILENAME=github_qr.png
      - FILL_COLOR=black
      - BACK_COLOR=white
    volumes:
      - ./qr_codes:/app/qr_codes
      